version: '3.3'
networks:
  tasks_net:
    driver: bridge
    ipam:
      config:
      - subnet: 183.120.120.1/20
services:
  tasks-web:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - tasks_net
  tasks-back:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    networks:
      tasks_net:
networks:
  tasks_net:
volumes:
  postgres-data: